// Built 2018-3-28 09:27:39
(function(b){b.matches=b.matches||b.mozMatchesSelector||b.msMatchesSelector||b.oMatchesSelector||b.webkitMatchesSelector;b.closest=b.closest||function(a){for(var c=this;c&&!c.matches(a);)c=c.parentElement;return c}})(Element.prototype);
var Lib=function(){var b={$:function(a,c){c=void 0===c?document:c;return c.querySelector(a)},$$:function(a,c){c=void 0===c?document:c;return c.querySelectorAll(a)},debounce:function(a,c,e){var d;return function(){var f=this,b=arguments,g=e&&!d;clearTimeout(d);d=setTimeout(function(){d=null;e||a.apply(f,b)},c);g&&a.apply(f,b)}},delegate:function(a,c,e,d,f){(void 0===f?0:f)?a.removeEventListener(c,function(a){}):a.addEventListener(c,function(a){if("array"===typeof e)for(var c=0,f=e.length;c<f;c++)a.target.closest(e)&&
d.call(this,a);else a.target.closest(e)&&d.call(this,a)})},setCookie:function(a,c,e){if(e){var d=new Date;d.setTime(d.getTime()+864E5*e);e="; expires="+d.toGMTString()}else e="";document.cookie=a+"="+c+e+"; path=/"},readCookie:function(a){a+="=";for(var c=document.cookie.split(";"),e=0;e<c.length;e++){for(var d=c[e];" "==d.charAt(0);)d=d.substring(1,d.length);if(0==d.indexOf(a))return d.substring(a.length,d.length)}return null},deleteCookie:function(a){b.setCookie(a,"",-1)},getOffset:function(a){a=
a.getBoundingClientRect();var c=document.body,e=document.documentElement;return{body:c,top:Math.round(a.top+(window.pageYOffset||e.scrollTop||c.scrollTop)-(e.clientTop||c.clientTop||0)),left:Math.round(a.left+(window.pageXOffset||e.scrollLeft||c.scrollLeft)-(e.clientLeft||c.clientLeft||0)),bottom:a.bottom,width:a.width,height:a.height}},getChildren:function(a,c){for(var e=[];a;a=a.nextSibling)1==a.nodeType&&a!=c&&e.push(a);return e},getSiblings:function(a){return b.getChildren(a.parentNode.firstChild,
a)},insertAfter:function(a,c){c.parentNode.insertBefore(a,c.nextSibling)},getParent:function(a,c){for(;a.parentNode;){if(a.parentNode.classList&&a.parentNode.classList.contains(c))return a.parentNode;a=a.parentNode}return null},fetch:function(a,c,e,d){var f=null,b=new XMLHttpRequest;c||(c={method:"GET",data:""});b.open(c.method,a,!0);b.setRequestHeader("X-Requested-With","XMLHttpRequest");"POST"==c.method&&b.setRequestHeader("Content-type","application/x-www-form-urlencoded");var g=[];b.ontimeout=
function(a){f=a};b.onreadystatechange=function(){e&&e.call&&(g=[null,e,d]);f&&g[2]&&g[2](f,b);if(4==b.readyState){var a=g[0|b.status/200];if(a){try{data=JSON.parse(b.responseText)}catch(c){data=b.statusText}a(data,b)}}};b.send(c.data);return b},colorLuminance:function(a){a=parseInt(a,16);return.2126*(a>>16&255)+.7152*(a>>8&255)+.0722*(a>>0&255)},shadeColor2:function(a,c){var b=parseInt(a.slice(1),16),d=0>c?0:255,f=0>c?-1*c:c,h=b>>16,g=b>>8&255,b=b&255;return"#"+(16777216+65536*(Math.round((d-h)*f)+
h)+256*(Math.round((d-g)*f)+g)+(Math.round((d-b)*f)+b)).toString(16).slice(1)},usort:function(a,c){var b=[],d="",f=0,h=!1,g={};"string"===typeof c?c=this[c]:"[object Array]"===Object.prototype.toString.call(c)&&(c=this[c[0]][c[1]]);g=(h="on"===(("undefined"!==typeof require?require("../info/ini_get")("locutus.sortByReference"):void 0)||"on"))?a:g;for(d in a)a.hasOwnProperty(d)&&(b.push(a[d]),h&&delete a[d]);try{b.sort(c)}catch(m){return!1}for(f=0;f<b.length;f++)g[f]=b[f];return h||g}};return b}(),
$=Lib.$,$$=Lib.$$,Upload=function(){var b={},a=null,c={},e=new XMLHttpRequest,d={progress:0,status:-1,message:!1},f=function(a){var c="Uploading...",b="#44AE73";if(0<=a.progress){switch(a.status){case 200:c="Upload complete. Searching for similar wallpapers...";break;case 404:c="Error 404! Upload destination not found.";b="#B94939";break;case 500:c="Error 500! Internal Server Error.";b="#B94939";break;case -1:c=a.progress+"%";break;default:c="Error "+a.status+"!",b="#B94939"}a.message&&(c=a.message);
DOM.open("div","upload_progress",["class","search-upload-progress"],"style",{width:a.progress+"%",backgroundColor:b});DOM.text(c);DOM.close("div")}else DOM.text("")},h=function(a){0<d.progress&&100>d.progress&&b.cancelUploadProgress();c.progressWrap.classList.remove("-show");document.getElementById(c.fileInputId).value=""},g=function(b){var d=b.target.files||b.dataTransfer.files;b.target.value.split("\\").pop()&&(m(d[0]),b=new FormData,b.append(c.fileInputId,a),e.open("POST",c.uploadPath,!0),e.setRequestHeader("X-FILENAME",
a.name),e.send(b))},m=function(g){a=g;d.progress=0;d.status=-1;d.message=!1;c.progressWrap.classList.add("-show");e.upload&&("image/jpeg"==a.type||"image/png"==a.type)&&5E6>=a.size?(DOM.patch(c.progressWrap,f,d),e.upload.addEventListener("progress",function(a){d.progress=parseInt(a.loaded/a.total*100);DOM.patch(c.progressWrap,f,d);"function"==typeof c.onProgress&&c.onProgress.call(a)}),e.onreadystatechange=function(a){4==e.readyState&&(a=e.responseText?JSON.parse(e.responseText):!1,b.xhr=e,a&&(d.progress=
100,"OK"==a.status?(d.status=e.status,"function"==typeof c.onSuccess&&c.onSuccess.call(b,a)):(d.status=0,d.message=a.messages[0],"function"==typeof c.onError&&c.onError.call(b,a)),DOM.patch(c.progressWrap,f,d)))}):(d.progress=100,d.status=0,d.message="JPG and PNG files only (smaller than 5Mb).",DOM.patch(c.progressWrap,f,d))};b.init=function(a){c=a;c.progressWrap.addEventListener("click",h);document.getElementById(c.fileInputId).addEventListener("change",g)};b.cancelUploadProgress=function(){e.abort()};
b.hideProgress=function(){d.progress=-1;c.progressWrap.classList.remove("-show")};return b}();(function(){"undefined"===typeof NodeList.prototype.forEach&&(NodeList.prototype.forEach=Array.prototype.forEach);"undefined"===typeof HTMLCollection.prototype.forEach&&(HTMLCollection.prototype.forEach=Array.prototype.forEach)})();
var DOM=function(){var b={};b.open=IncrementalDOM.elementOpen;b.close=IncrementalDOM.elementClose;b.void=IncrementalDOM.elementVoid;b.patch=IncrementalDOM.patch;b.text=IncrementalDOM.text;return b}(),Home=function(){var b={},a=null,c=null,e=function(b){c=c||document.getElementById("image_file");c.setAttribute("type","hidden");c.value=b.id;d();a.submit()},d=function(){c=c||document.getElementById("image_file");var a=document.getElementById("color_value");""==c.value&&c.removeAttribute("name");""==
a.value&&a.removeAttribute("name")};b.onFeaturedInView=function(){if(this.isInViewport){var a=this.watchItem.dataset.img;this.watchItem.style.backgroundImage=a?"url("+a+")":""}};b.init=function(){a=document.getElementById("filter_form");Upload.init({progressWrap:$(".search-upload-progress-wrap"),uploadPath:"/search/upload",fileInputId:"image_file",onSuccess:e});$$(".feat-cell").forEach(function(a){a=scrollMonitor.create(a);a.stateChange(b.onFeaturedInView);b.onFeaturedInView.call(a)});a.addEventListener("submit",
d);$(".home-search-input").focus()};return b}(),MoreLikeThis=function(){var b="",a={root_class:"thumb-mlt _T",control_l_class:"mlt-control -l -hidden _T",control_r_class:"mlt-control -r -hidden _T"},c=null,e=null,d=0,f=0,h=0,g=null,m=null,k={visible:!1,barwrap:null},n=function(a){g=a.target.parentNode.parentNode;a=Lib.getOffset(g);for(var c=g.dataset.id,b=g,d=null;b;){if("#text"!=b.nodeName)if(Lib.getOffset(b).top<=a.top+a.height/2)d=b;else break;b=b.nextSibling}r(d,c,a)},p=function(a){fastdom.measure(function(){var c=
f-d+140;h="l"==a.target.dataset.d?h-600:h+600;h=Math.max(0,Math.min(h,c));fastdom.mutate(function(){e.style.transform="translate3d(-"+h+"px, 0, 0)"})})},l=function(b){var n=[],l=OPT.filter_values.purity,l=(1<l.length?0:-1<l.indexOf("safe")?1:0)||0;m=Lib.fetch("/wallpaper/morelikethis/"+b+"/25/0/"+l,null,function(b){if(b.ok){b=b.message.docs;if(0<b.length)for(var l=0,r=b.length;l<r;l++)n[l]={id:b[l].id,key:l,th_size:b[l].th_size,sources:b[l].sources,tags:b[l].tags,colors:b[l].colors,wh:b[l].sizes,
src:OPT.url.thumb_small+"/"+b[l].id[0].toLowerCase()+"/"+b[l].id+".jpg",faved:b[l].faved||0};a.thumbs=n;a.loading=!1;DOM.patch(k.barwrap,q);c=$(".thumb-mlt");e=$(".thumb-mlt .content");d=c.offsetWidth+80;f=c.scrollWidth;f>d?(a.control_l_class="mlt-control -l _T",a.control_r_class="mlt-control -r _T",DOM.patch(k.barwrap,q,a),$(".mlt-control.-l").addEventListener("click",p),$(".mlt-control.-r").addEventListener("click",p)):(a.control_l_class="mlt-control -l -hidden _T",a.control_r_class="mlt-control -r -hidden _T",
DOM.patch(k.barwrap,q,a),$(".mlt-control.-l").removeEventListener("click",p),$(".mlt-control.-r").removeEventListener("click",p))}else console.error("MLT error:",b.message)},function(a){console.error("MLT error:",a)})},q=function(){DOM.void("div","root_arrow",["class","thumb-mlt-arrow _T"],"style",a.root_arrow_styles);DOM.open("div","root",null,"class",a.root_class,"style",a.root_styles);DOM.void("div","ctrll",["data-d","l"],"class",a.control_l_class);DOM.void("div","ctrlr",["data-d","r"],"class",
a.control_r_class);DOM.open("div","content",["class","content _T"]);if(a.thumbs&&0<a.thumbs.length)for(var b=0,c=a.thumbs.length;b<c;b++)DOM.open("div",a.thumbs[b].key,["class","mlt-thumb _T"],"data-id",a.thumbs[b].id,"data-tags",a.thumbs[b].tags,"data-wh",a.thumbs[b].wh,"data-sources",a.thumbs[b].sources,"data-colors",a.thumbs[b].colors,"data-faved",a.thumbs[b].faved,"style",{width:a.thumbs[b].th_size[0]+"px",height:a.thumbs[b].th_size[1]+"px"}),a.thumbs[b].faved&&(DOM.open("div","mlt-thumb-faved",
["class","thumb-faved","title","In your favorites"]),DOM.text("\u2605"),DOM.close("div")),DOM.open("a","tha",["class","mlt-thumb-a _T","target","_blank"],"href","/wallpaper/"+a.thumbs[b].id),DOM.void("img","thimg",["class","mlt-thumb-img _T"],"src",a.thumbs[b].src,"width",a.thumbs[b].width,"height",a.thumbs[b].height),DOM.close("a"),DOM.close("div");else a.loading?(DOM.open("div","loader",["class","la-ball-beat la-2x _T"]),DOM.void("div"),DOM.void("div"),DOM.void("div"),DOM.void("div")):(DOM.open("div",
"notfound",["class","notfound-wrap"]),DOM.void("div","nfico",["class","g notfound-icon"]),DOM.open("div","nftext",["class","notfound-text"]),DOM.text("I found nothing..."),DOM.close("div")),DOM.close("div");DOM.close("div");DOM.close("div")},r=function(c,d,f){function e(a){p=h+10;h<m?(window.scrollTo(0,h),window.requestAnimationFrame(e),h=p+10):window.scroll(0,m)}a.id=d;if(k.visible)b!=d&&setTimeout(function(){r(c,d,f)},170);else{var n=0>OPT.area.indexOf("user_favorites")?f.left+parseInt(f.width/
2)-15:f.left+parseInt(f.width/2)-315;a.root_arrow_styles={left:n+"px"};g.classList.add("-mlt-selected");k.barwrap=document.createElement("div");k.barwrap.className="thumb-mlt-wrap";Lib.insertAfter(k.barwrap,c);var p=window.pageYOffset||document.documentElement.scrollTop||document.body.scrollTop,n=k.barwrap.getBoundingClientRect(),n=window.innerHeight-(n.bottom+300),h=p,m=p+10+Math.abs(n);10>n&&window.requestAnimationFrame(e);a.loading=!0;DOM.patch(k.barwrap,q,a);setTimeout(function(){l(d)},160);setTimeout(function(){a.root_class=
"thumb-mlt _T -show";DOM.patch(k.barwrap,q,a);k.visible=!0;b=d},1)}};k.init=function(){OPT.thumb_mlt&&Lib.delegate($(".thumbs-wrap"),"click",".mlt-link",n)};k.hide=function(){a.root_class="thumb-mlt _T";DOM.patch(k.barwrap,q,a);document.getElementById("wallbox")&&InlineWallpaper.close();g.classList.remove("-mlt-selected");m&&4!=m.readyState&&m.abort();setTimeout(function(){k.barwrap.remove();k.barwrap=null;k.visible=!1;b="";a={root_class:"thumb-mlt _T",control_l_class:"mlt-control -l -hidden _T",
control_r_class:"mlt-control -r -hidden _T"};e=c=null;h=f=d=0},150)};return k}(),Filters=function(){var b={},a=OPT.filter_values?OPT.filter_values:{purity:["safe"],reso:[],cust_reso:"",reso_atleast:0,ratio:[],cust_ratio:"",order:""},c=null,e="",d=function(b,c){""==b||""==c?a.cust_reso="":isNaN(b)||isNaN(c)?a.cust_reso="":a.cust_reso=parseInt(b)+"x"+parseInt(c)},f=function(b){var c=b.target.type,d=b.target.dataset.name,f=b.target.checked,e=b.target.value;if(d){var g=$('.form-wrap input[name="'+d+'"]');
if("radio"==c){for(var h=$$(".selected",b.target.parentNode.parentNode),k=0,m=h.length;k<m;k++)h[k].classList.remove("selected");b.target.parentNode.classList.add("selected");a[d]=e;g.value=a[d]}else f?(b.target.parentNode.classList.add("selected"),-1==a[d].indexOf(e)&&a[d].push(e)):(b.target.parentNode.classList.remove("selected"),b=a[d].indexOf(e),a[d].splice(b,1)),g.value=a[d].join("_");console.log(d,e,f,c);console.log(a)}},h=function(b){var c=b.target.dataset.type,d=b.target.dataset.name,f=b.target.dataset.value,
e=b.target.classList.contains("selected");if(d){var g=$('.form-wrap input[name="'+d+'"]');if("radio"==c){for(var c=$$(".selected",b.target.parentNode),e=0,h=c.length;e<h;e++)c[e].classList.remove("selected");b.target.classList.add("selected");a[d]=f;g.value=a[d]}else e?(b.target.classList.remove("selected"),b=a[d].indexOf(f),a[d].splice(b,1)):(b.target.classList.add("selected"),-1==a[d].indexOf(f)&&a[d].push(f)),g.value=a[d].join("_")}},g=function(b){var c=b.target.dataset.name;b=Lib.getSiblings(b.target);
for(var f=$('.form-wrap input[name="cust_'+c+'"]'),e=[],g=0,h=b.length;g<h;g++)e.push(b[g].value);"reso"==c?2==e.length?d(e[0],e[1]):a.cust_reso="":a["cust_"+c]=e;f.value=a["cust_"+c];if(c=Lib.getParent(f,"select-wrap"))$(".chck",c).checked=!1},m=function(b){var c=["_ord","_atleast"],f=document.activeElement,e=document.getElementById("filter_form");if(f.classList.contains("input-custom")){b.preventDefault();switch(f.dataset.id){case "reso_width":case "reso_height":e=$(".cust-reso-width").value.trim();
c=$(".cust-reso-height").value.trim();d(e,c);$('.form-wrap input[name="cust_reso"]').setAttribute("value",a.cust_reso);break;case "ratio":e=$(".input-custom.cust-ratio").value,a.cust_ratio=e,$('.form-wrap input[name="cust_ratio"]').setAttribute("value",a.cust_ratio)}if(f=Lib.getParent(f,"select-wrap"))$(".chck",f).checked=!1}else{""==document.getElementById("color_value").value&&c.push("color");""==document.getElementById("image_file").value&&c.push("image_file");""==a.cust_reso&&c.push("cust_reso");
""==a.cust_ratio&&c.push("cust_ratio");f=0;for(b=c.length;f<b;f++)$$('input[name="'+c[f]+'"]').forEach(function(a){a.name=""});f=$(".search-input");"category"!=OPT.area&&""!=document.getElementById("color_value").value?e.setAttribute("action","/search"):"random"==OPT.area&&""!=f.value?e.setAttribute("action","/search"):""!=document.getElementById("image_file").value&&e.setAttribute("action","/search")}},k=function(a){a=$(".search-color-picker-wrap");var b=document.getElementById("color_value").value;
a.style.display="block"==a.style.display?"none":"block";c.setHex(b?"#"+b:"#ffffff")};b.init=function(){var a=document.getElementById("filter_form");if(!1!==OPT.filter_values){var b=$(".form-wrap");Lib.delegate(b,"change",".chck._Y",f);Lib.delegate(b,"click",".list-item",h);Lib.delegate(b,"click",".cust-apply",g);document.getElementById("filter_form").addEventListener("submit",m);var d=$(".lum-slider"),q=$(".hidden_luminosity").value.split("_");setTimeout(function(){noUiSlider.create(d,{start:[parseInt(q[0]),
parseInt(q[1])],connect:!0,behaviour:"drag",step:1,margin:5,range:{min:0,max:100},format:{to:function(a){return parseInt(a)},from:function(a){return parseInt(a)}},tooltips:[!0,!0],orientation:"horizontal"});d.noUiSlider.on("update",function(a,b){var c=parseInt(a[0])+"_"+parseInt(a[1]);$('input[name="luminosity"]').setAttribute("value",c)})},500)}setTimeout(function(){function a(b){b.preventDefault();$(".search-image-icon.-selected").removeEventListener("click",a);f.classList.remove("-selected");f.removeAttribute("style");
g.setAttribute("type","file");g.value="";return!1}var b=document.getElementById("color_value"),d=$(".search-color-icon"),f=$(".search-image-icon"),g=document.getElementById("image_file");Upload.init({progressWrap:$(".search-upload-progress-wrap"),uploadPath:"/search/upload",fileInputId:"image_file",onSuccess:function(b){f.classList.add("-selected");f.style.backgroundImage="url(/uploads/"+b.id+".jpg)";g.setAttribute("type","hidden");g.value=b.id;$(".search-image-icon.-selected").addEventListener("click",
a);this.hideProgress()}});OPT.filter_values.image&&$(".search-image-icon.-selected").addEventListener("click",a);c=ColorPicker($(".search-color-picker-wrap"),function(a,c,f){e=a.replace("#","");b.value=e;d.style.color=a})},300);Lib.delegate(a,"click",".search-color-icon",k)};return b}(),Settings=function(){var b={obj:{}},a=function(a){var e=!1;switch(a.target.dataset.name){case "infscroll":b.obj.infscroll=a.target.checked?1:0;e="infscroll";break;case "qf":var d=[];$$(".ch-qf").forEach(function(a){a.checked&&
d.push(a.value)});b.obj.qf=d;break;case "thpp":$$(".ch-ipp").forEach(function(a){a.checked=!1}),a.target.checked=!0,e="thpp",b.obj.thpp=a.target.value}Lib.setCookie("settings",encodeURIComponent(JSON.stringify(b.obj)),365);OPT.user.loggedin&&!1!==e&&Lib.fetch("/user/sync_settings/"+e,null,function(a){a.ok?console.dir(a):console.log("err",a.message)},function(a){console.log("error",a)})};b.init=function(){b.obj=decodeURIComponent(Lib.readCookie("settings"));b.obj&&"null"!=b.obj?b.obj=JSON.parse(b.obj):
(b.obj={qf:["anime"],thpp:32,infscroll:0},Lib.setCookie("settings",encodeURIComponent(JSON.stringify(b.obj)),365));Lib.delegate($(".top-user-wrap .user-menu"),"click",".chck",a)};return b}(),Wallhalla=function(){var b={};b.filterbarON=OPT.filters_visible;b.adblockEnabled=!1;var a=function(a){a=a||window.event;var b=a.target||a.srcElement;a=$$(".chck._X");var c=a.length;document.getElementById("wallbox")&&(b.classList.contains("_I")||InlineWallpaper.close());OPT.thumb_mlt&&MoreLikeThis.visible&&(b.classList.contains("_T")||
b.classList.contains("_I")||MoreLikeThis.hide());if(b.classList&&b.classList.contains("chck")){if(!b.checked&&!b.classList.contains("_Y"))for(b=0;b<c;b++)a[b].checked=!1}else{for(;b;){if(b&&b.classList&&(b.classList.contains("_Y")||b.classList.contains("_X")))return;b=b.parentNode}for(b=0;b<c;b++)a[b].checked=!1}},c=function(a){new SimpleBar($(".bmenu-categories"));document.getElementById("main_menu_check").removeEventListener("click",c)},e=function(a){a=a.target;a.classList.contains("search-settings")?
a.classList.toggle("selected"):a.parentNode.classList.toggle("selected");a=$(".filterbar");b.filterbarON?(a.classList?(a.classList.remove("-show"),a.classList.remove("-noanim")):a.className=a.className.replace(/(^|\b)-show(\b|$)/gi," "),b.filterbarON=!1):(a.classList?a.classList.add("-show"):a.className+=" -show",b.filterbarON=!0);if(Favorites)Favorites.onScroll()};b.onThumbInView=function(){this.watchItem.src=this.isInViewport?this.watchItem.dataset.src:"/images/pixel.gif"};b.init=function(){"wallpaper"!=
OPT.area&&(Settings.init(),Filters.init(),document.addEventListener("mousedown",a),"home"==OPT.area?Home.init():(MoreLikeThis.init(),$(".search-settings").addEventListener("click",e),document.getElementById("main_menu_check").addEventListener("click",c),$$(".lazyload").forEach(function(a){a=scrollMonitor.create(a);a.stateChange(b.onThumbInView);b.onThumbInView.call(a)})))};return b}();Wallhalla.init();
